# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  Version.Major: 0
  Version.Minor: 0
  Version.Patch: 1
  Version.MajorMinorPatch: $(Version.Major).$(Version.Minor).$(Version.Patch)
  Version.Revision: $[counter(variables['Version.MajorMinorPatch'],0)]
  buildConfiguration: 'Release'

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  name: default

steps: 

- script: dotnet pack --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet pack $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'